language: go
dist: bionic
go:
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.14"
  - "1.15"
  - master
os:
  - linux
  - osx
  - windows
jobs:
  allow_failures:
    - go: master
  fast_finish: true
script:
  - go test -v -cover
